image:
  repository: stupid-auth
  tag: latest
env:
  TZ: Europe/Amsterdam
  AUTH_DOMAIN: example.com
service:
  main:
    ports:
      http:
        port: 8000
ingress:
  main:
    enabled: true
    annotations:
      external-dns.home.arpa/enabled: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - host: stupid-auth.example.com
      paths:
      - path: /
        pathType: Prefix
    tls:
      - hosts:
        - stupid-auth.example.com
        secretName: stupid-auth-tls
persistence:
  secret-file:
    enabled: true
    type: secret
    name: stupid-auth-users
    subPath: users.yaml
    mountPath: /users.yaml
    readOnly: true
podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: OnRootMismatch
  supplementalGroups: [10000]
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    memory: 500Mi
