name: release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # - run: nix flake check --impure
      - run: nix build .#docker
      - run: nix run .#publish-docker
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
